# Generated by Django 5.2.16 on 2026-07-15 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_pending_details',
            field=models.BooleanField(default=False, verbose_name='يوجد تعديل معلق'),
        ),
        migrations.AddField(
            model_name='project',
            name='pending_details',
            field=models.TextField(blank=True, default='', verbose_name='تفاصيل مقترحة'),
        ),
        migrations.AddField(
            model_name='project',
            name='pending_details_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاقتراح'),
        ),
        migrations.AddField(
            model_name='project',
            name='pending_details_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_details', to=settings.AUTH_USER_MODEL, verbose_name='مقترح بواسطة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='الأيقونة'),
        ),
    ]
