# Generated by Django 5.2.16 on 2026-07-15 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to=settings.AUTH_USER_MODEL, verbose_name='رفعه'),
        ),
    ]
