# Generated by Django 5.2.16 on 2026-07-16 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUpdateRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_at', models.DateTimeField(verbose_name='آخر اطلاع')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_reads', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'user'), name='unique_project_user_read')],
            },
        ),
        migrations.CreateModel(
            name='TaskSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الاطلاع')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_marks', to='core.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('task', 'user'), name='unique_task_user_seen')],
            },
        ),
    ]
