# Generated by Django 5.2.16 on 2026-07-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_read_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupdate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ النقل للمحذوفات'),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ النقل للمحذوفات'),
        ),
    ]
