# Generated by Django 5.2.16 on 2026-07-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_projectupdate_deleted_at_task_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='share_link',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='رابط الشير'),
        ),
    ]
