# Generated by Django 5.2.16 on 2026-07-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_project_share_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='category',
            field=models.CharField(blank=True, choices=[('OUTGOING', 'صادر'), ('INCOMING', 'وارد'), ('ACCOUNTS', 'حسابات'), ('OFFER', 'عرض'), ('QUOTATION', 'Quotation'), ('DATASHEET', 'Datasheet'), ('MANUAL', 'Manual')], default='', max_length=20, verbose_name='التصنيف'),
        ),
    ]
