# Generated by Django 5.2.16 on 2026-07-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_attachment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='accounts_link',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='رابط ملف الحسابات'),
        ),
        migrations.AddField(
            model_name='project',
            name='incoming_link',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='رابط مجلد الواردة'),
        ),
        migrations.AddField(
            model_name='project',
            name='outgoing_link',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='رابط ملف الصادر'),
        ),
    ]
