# Generated by Django 5.2.16 on 2026-07-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_project_archived_at_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'مهمة مسندة'), ('TASK_STATUS', 'تغيير حالة مهمة'), ('NEW_COMMENT', 'تعليق جديد'), ('MENTION', 'إشارة في تعليق'), ('DETAILS_PROPOSED', 'تعديل مقترح'), ('PROJECT_UPDATE', 'تحديث مشروع')], max_length=20, verbose_name='النوع'),
        ),
    ]
