# Generated by Django 5.2.16 on 2026-07-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='تاريخ الاستحقاق'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'عالية'), ('MEDIUM', 'متوسطة'), ('LOW', 'منخفضة')], db_index=True, default='MEDIUM', max_length=10, verbose_name='الأولوية'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'مهمة مسندة'), ('TASK_STATUS', 'تغيير حالة مهمة'), ('NEW_COMMENT', 'تعليق جديد'), ('MENTION', 'إشارة في تعليق'), ('DUE_SOON', 'اقتراب استحقاق'), ('DETAILS_PROPOSED', 'تعديل مقترح'), ('PROJECT_UPDATE', 'تحديث مشروع')], max_length=20, verbose_name='النوع'),
        ),
    ]
