# Generated by Django 5.2.16 on 2026-07-17 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_task_due_date_task_priority_alter_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='core.projectupdate', verbose_name='التحديث'),
        ),
    ]
