# Generated by Django 5.2.16 on 2026-07-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_attachment_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/thumbs/', verbose_name='مصغّرة الصورة'),
        ),
    ]
