# Generated by Django 5.2.16 on 2026-07-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_user_photo_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='attachments/thumbs/%Y/%m/', verbose_name='المصغّرة'),
        ),
    ]
