# Generated by Django 5.2.16 on 2026-07-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_attachment_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'مهمة مسندة'), ('TASK_STATUS', 'تغيير حالة مهمة'), ('TASK_SUGGESTED', 'مهمة مقترحة'), ('NEW_COMMENT', 'تعليق جديد'), ('MENTION', 'إشارة في تعليق'), ('DUE_SOON', 'اقتراب استحقاق'), ('DETAILS_PROPOSED', 'تعديل مقترح'), ('PROJECT_UPDATE', 'تحديث مشروع')], max_length=20, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('SUGGESTED', 'مقترحة'), ('OPEN', 'مفتوحة'), ('IN_PROGRESS', 'قيد الإنجاز'), ('REVIEW', 'قيد المراجعة'), ('DONE', 'منجزة')], db_index=True, default='OPEN', max_length=20, verbose_name='الحالة'),
        ),
    ]
