# Generated by Django 5.2.16 on 2026-07-17 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_notification_kind_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True, verbose_name='نقطة النهاية')),
                ('p256dh', models.CharField(max_length=200, verbose_name='مفتاح p256dh')),
                ('auth', models.CharField(max_length=100, verbose_name='مفتاح auth')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'اشتراك دفع',
                'verbose_name_plural': 'اشتراكات الدفع',
            },
        ),
    ]
