# Generated by Django 5.2.16 on 2026-07-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurrence',
            field=models.CharField(choices=[('NONE', 'بلا تكرار'), ('DAILY', 'يومياً'), ('WEEKLY', 'أسبوعياً'), ('MONTHLY', 'شهرياً')], default='NONE', max_length=10, verbose_name='التكرار'),
        ),
    ]
