# Generated by Django 5.2.16 on 2026-07-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_task_recurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('SUGGESTED', 'مقترحة'), ('OPEN', 'مفتوحة'), ('IN_PROGRESS', 'قيد الإنجاز'), ('ON_HOLD', 'قيد الانتظار'), ('REVIEW', 'قيد المراجعة'), ('DONE', 'منجزة')], db_index=True, default='OPEN', max_length=20, verbose_name='الحالة'),
        ),
    ]
