# Generated by Django 5.2.16 on 2026-07-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project_order',
            field=models.JSONField(blank=True, default=list, verbose_name='ترتيب المشاريع'),
        ),
    ]
