# Generated by Django 5.2.16 on 2026-07-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_user_project_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_link',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='رابط الذكاء الاصطناعي'),
        ),
    ]
