# Generated by Django 5.2.16 on 2026-07-19 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_project_ai_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='core.task', verbose_name='المهمة'),
        ),
    ]
