# Generated by Django 5.2.16 on 2026-07-20 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_attachment_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='email_tag',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='وسم المشروع'),
        ),
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, verbose_name='عنوان البريد الإلكتروني')),
                ('password', models.CharField(max_length=255, verbose_name='كلمة المرور')),
                ('imap_host', models.CharField(default='imap.gmail.com', max_length=255, verbose_name='خادم الاستلام IMAP')),
                ('imap_port', models.PositiveIntegerField(default=993, verbose_name='منفذ IMAP')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='خادم الإرسال SMTP')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='منفذ SMTP')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_account', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حساب بريد',
                'verbose_name_plural': 'حسابات البريد',
            },
        ),
    ]
