# Generated by Django 5.2.16 on 2026-07-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_project_email_tag_emailaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='auth_method',
            field=models.CharField(choices=[('PASSWORD', 'كلمة مرور تطبيق'), ('GOOGLE', 'حساب Google (OAuth)')], default='PASSWORD', max_length=10, verbose_name='طريقة الربط'),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='google_access_token',
            field=models.TextField(blank=True, default='', verbose_name='Google access token'),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='google_refresh_token',
            field=models.TextField(blank=True, default='', verbose_name='Google refresh token'),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='google_token_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='انتهاء التوكن'),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='كلمة المرور'),
        ),
    ]
