# Generated by Django 5.2.16 on 2026-07-20 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_emailaccount_auth_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(choices=[('received', 'الوارد'), ('sent', 'الصادر')], max_length=10, verbose_name='المجلد')),
                ('uidvalidity', models.BigIntegerField(default=0, verbose_name='UIDVALIDITY')),
                ('uid', models.BigIntegerField(verbose_name='UID')),
                ('message_id', models.CharField(blank=True, default='', max_length=500, verbose_name='Message-ID')),
                ('subject', models.TextField(blank=True, default='', verbose_name='الموضوع')),
                ('sender', models.TextField(blank=True, default='', verbose_name='المرسِل')),
                ('recipient', models.TextField(blank=True, default='', verbose_name='المستلِم')),
                ('body', models.TextField(blank=True, default='', verbose_name='النص')),
                ('date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الإرسال')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='وقت المزامنة')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='core.project', verbose_name='المشروع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رسالة بريد',
                'verbose_name_plural': 'رسائل البريد',
                'ordering': ['-date', '-uid'],
                'indexes': [models.Index(fields=['user', 'folder', '-date'], name='core_emailm_user_id_0eb3f2_idx'), models.Index(fields=['user', 'project'], name='core_emailm_user_id_8f1688_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'folder', 'uidvalidity', 'uid'), name='unique_email_per_user_folder_uid')],
            },
        ),
        migrations.CreateModel(
            name='EmailSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(choices=[('received', 'الوارد'), ('sent', 'الصادر')], max_length=10, verbose_name='المجلد')),
                ('uidvalidity', models.BigIntegerField(default=0, verbose_name='UIDVALIDITY')),
                ('last_uid', models.BigIntegerField(default=0, verbose_name='آخر UID مُزامَن')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_sync_states', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حالة مزامنة بريد',
                'verbose_name_plural': 'حالات مزامنة البريد',
                'constraints': [models.UniqueConstraint(fields=('user', 'folder'), name='unique_sync_state_per_user_folder')],
            },
        ),
    ]
